name: Update GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *" # runs daily at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      # GitHub Stats using a simpler, more reliable action
      - name: GitHub Readme Stats
        uses: jstrieb/github-stats@v1
        with:
          USERNAME: ${{ github.repository_owner }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: "Updated GitHub Stats"
          
      # Generate activity graph
      - name: Generate Activity Graph
        uses: ashutosh00710/github-readme-activity-graph@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          theme: tokyo-night
          area: true
          hide_border: true 
