name: Update GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *" # runs daily at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # GitHub Stats Card
      - name: GitHub Stats
        uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "False"
          SHOW_SHORT_INFO: "True"
          
      # Metrics and activity graphs  
      - name: Metrics and Activity
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: SagitaKDX
          config_timezone: Asia/Ho_Chi_Minh
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories
          plugin_lines: yes
          plugin_languages: yes
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
